/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /Users/Ronan/ros_for_ios/ros/introlab-ros-pkg/x264_image_transport/msg/x264Packet.msg
 *
 */


#ifndef X264_IMAGE_TRANSPORT_MESSAGE_X264PACKET_H
#define X264_IMAGE_TRANSPORT_MESSAGE_X264PACKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace x264_image_transport
{
template <class ContainerAllocator>
struct x264Packet_
{
  typedef x264Packet_<ContainerAllocator> Type;

  x264Packet_()
    : header()
    , data()
    , img_width(0)
    , img_height(0)  {
    }
  x264Packet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)
    , img_width(0)
    , img_height(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;

   typedef int32_t _img_width_type;
  _img_width_type img_width;

   typedef int32_t _img_height_type;
  _img_height_type img_height;




  typedef boost::shared_ptr< ::x264_image_transport::x264Packet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::x264_image_transport::x264Packet_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct x264Packet_

typedef ::x264_image_transport::x264Packet_<std::allocator<void> > x264Packet;

typedef boost::shared_ptr< ::x264_image_transport::x264Packet > x264PacketPtr;
typedef boost::shared_ptr< ::x264_image_transport::x264Packet const> x264PacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::x264_image_transport::x264Packet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::x264_image_transport::x264Packet_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace x264_image_transport

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/Users/Ronan/ros_for_ios/ros/ros_msgs/std_msgs/msg/'], 'x264_image_transport': ['/Users/Ronan/ros_for_ios/ros/introlab-ros-pkg/x264_image_transport/msg/']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::x264_image_transport::x264Packet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::x264_image_transport::x264Packet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::x264_image_transport::x264Packet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::x264_image_transport::x264Packet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::x264_image_transport::x264Packet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::x264_image_transport::x264Packet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::x264_image_transport::x264Packet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "325d70e7ecc52530d057d7dda8aeb84f";
  }

  static const char* value(const ::x264_image_transport::x264Packet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x325d70e7ecc52530ULL;
  static const uint64_t static_value2 = 0xd057d7dda8aeb84fULL;
};

template<class ContainerAllocator>
struct DataType< ::x264_image_transport::x264Packet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "x264_image_transport/x264Packet";
  }

  static const char* value(const ::x264_image_transport::x264Packet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::x264_image_transport::x264Packet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header     # Original sensor_msgs/Image header\n\
uint8[] data      # x264 NAL unit\n\
int32 img_width   # Image width\n\
int32 img_height  # Image height\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const ::x264_image_transport::x264Packet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::x264_image_transport::x264Packet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
      stream.next(m.img_width);
      stream.next(m.img_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct x264Packet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::x264_image_transport::x264Packet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::x264_image_transport::x264Packet_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "img_width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.img_width);
    s << indent << "img_height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.img_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // X264_IMAGE_TRANSPORT_MESSAGE_X264PACKET_H
